# global evaluation settings
timeout_seconds: 18000
max_workers: 4 # number of parallel instances for local running
# result_dir: "./results"
result_dir: "./results-satlib"
# result_dir: "./results/local_tests"

# absolute or relative paths to benchmark directories
benchmark_dirs:
  # - "./benchmarks-mse24/single-test-instance"
  # - "./benchmarks-mse24/sample-test-instances"
  # - "./benchmarks-mse24/mse24-exact-weighted"
  # - "./benchmarks-mse24/random-50-benchmarks"
  - "./benchmarks-satlib/sample-test-instances"
  - "./benchmarks-satlib/uf250_1_1-compressed"
  - "./benchmarks-satlib/uf250_10_10-compressed"
  - "./benchmarks-satlib/uf250_25_25-compressed"
  - "./benchmarks-satlib/uf250_100_100-compressed"

# dictioanry of solvers to evaluate
# format: ShortName: "path/to/starexec/run/script"
solvers:
  WMaxCDCL2024: "./solvers/WMaxCDCL2024/bin/starexec_run_wmaxcdcl-openwbo1200"
  # CASHWMaxSAT-DisjCad-S6: "./solvers/CASHWMaxSAT-DisjCad-S6/bin/starexec_run_default"
  # CASHWMaxSAT-DisjCom-S9: "./solvers/CASHWMaxSAT-DisjCom-S9/bin/starexec_run_default"
  # EvalMaxSAT_2024: "./solvers/EvalMaxSAT_2024/bin/starexec_run_EvalMaxSAT"
  # you can append future solvers easily
